name: Release and Publish to NPM 
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Initialize Git user
        run: |
            git config --global user.email "diego.tonini93@gmail.com"
            git config --global user.name "Diego Tonini"
      
      - name: Initialize the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN ${{ secrets.NPM_TOKEN }}

      - name: Run release
        run: npm run release --ci
        env:
          GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN ${{ secrets.NPM_TOKEN }}

      - name: End message
        run: echo 'All done!'